services:
  # Customer Service - Simple PHP
  customer-service:
    build:
      context: ./services/customer-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - evm_network

  # Warranty Service - Simple PHP  
  warranty-service:
    build:
      context: ./services/warranty-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - evm_network

  # Vehicle Service - Simple PHP
  vehicle-service:
    build:
      context: ./services/vehicle-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - evm_network

  # Admin Service - Simple PHP
  admin-service:
    build:
      context: ./services/admin-service
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    networks:
      - evm_network

  # Notification Service - Simple PHP
  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    networks:
      - evm_network

networks:
  evm_network:
    driver: bridge