CREATE TABLE IF NOT EXISTS claims (
	id CHAR(36) PRIMARY KEY,
	vin VARCHAR(64) NOT NULL,
	customer_id INT NOT NULL,
	status ENUM('PENDING','APPROVED','REJECTED','IN_PROGRESS','CLOSED') NOT NULL DEFAULT 'PENDING',
	description TEXT,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_claims_vin ON claims(vin);
CREATE INDEX idx_claims_status ON claims(status);